apiVersion: v1
kind: ConfigMap
metadata:
  name: fla-api-config
data:
  ENVIRONMENT: production
  ACCESS_TOKEN_EXPIRE_MINUTES: "60"
  LOG_LEVEL: INFO
  DB_HOST: postgres-rw.fla.svc.cluster.local
  DB_PORT: "5432"
  DB_NAME: fla
  REDIS_HOST: redis.fla.svc.cluster.local
  REDIS_PORT: "6379"
