apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  redis.conf: |
    save 900 1
    save 300 10
    appendonly yes
    appendfsync everysec
    maxmemory 512mb
    maxmemory-policy allkeys-lru

  sentinel.conf: |
    sentinel monitor fla-master redis-0.redis-headless.fla.svc.cluster.local 6379 2
    sentinel down-after-milliseconds fla-master 5000
    sentinel failover-timeout fla-master 60000
    sentinel parallel-syncs fla-master 1
