apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fla

resources:
  - namespace.yaml
  - ../../base

patches:
  - path: patches/api-resources.yaml
  - path: patches/worker-llm-resources.yaml

images:
  - name: ghcr.io/org/fla-api
    newTag: latest
  - name: ghcr.io/org/fla-frontend
    newTag: latest
