apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: fla-tls
spec:
  secretName: fla-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - fla.your-domain.com
