apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fla

commonLabels:
  app.kubernetes.io/part-of: failure-log-analyzer
  app.kubernetes.io/managed-by: kustomize

resources:
  - namespace.yaml
  - api/deployment.yaml
  - api/service.yaml
  - api/hpa.yaml
  - api/configmap.yaml
  - worker/deployment-rule.yaml
  - worker/deployment-llm.yaml
  - worker/hpa-rule.yaml
  - worker/hpa-llm.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
  - frontend/hpa.yaml
  - postgres/cluster.yaml
  - postgres/scheduled-backup.yaml
  - redis/statefulset.yaml
  - redis/service-headless.yaml
  - redis/service.yaml
  - redis/configmap.yaml
  - ingress/ingress.yaml
  - ingress/certificate.yaml
